app:
  build: .
  environment:
    - LEIN_USERNAME
    - LEIN_PASSWORD
    - USPS_DATOMIC_URI
    - USPS_SQS_QUEUE
    - USPS_SQS_FAIL_QUEUE
    - USPS_SQS_REGION
    - AWS_ACCESS_KEY
    - AWS_SECRET_KEY
  links:
    - rabbitmq
    - datomic
rabbitmq:
  image: rabbitmq:3.4.3-management
datomic:
  image: quay.io/democracyworks/datomic-tx:0.9.5130
