app:
  build: .
  environment:
    - USPS_DATOMIC_URI
    - USPS_SQS_QUEUE
    - USPS_SQS_FAIL_QUEUE
    - USPS_SQS_REGION
    - AWS_ACCESS_KEY
    - AWS_SECRET_KEY
  links:
    - wildfly
rabbitmq:
  image: rabbitmq:3.5.0-management
wildfly:
  image: quay.io/democracyworks/wildfly:8.2.0.Final
  links:
    - rabbitmq
  ports:
    - 9990
    - 8080
  environment:
    ADMIN_USERNAME: admin
    ADMIN_PASSWORD: admin
